@baseUrl = http://localhost:3000/

### AppController->Home
# @name AppControllerHome
GET {{baseUrl}}hello/world


### BaseManualController->getHello
# @name BaseManualControllerHome
GET {{baseUrl}}


### BaseCliController->home
# @name BaseCliControllerHome
GET {{baseUrl}}/base-cli


### BaseCliController->about
# @name BaseCliControllerAbout
GET {{baseUrl}}base-cli/about


# --------- GAMES ---------------

### GamesController->all
# @name GamesControllerAll
GET {{baseUrl}}games?pagination=5&offset=3


### GamesController->findOne
GET {{baseUrl}}games/1


### GamesController->findOneByCategory
# @name GamesControllerByCategoryNameAndId
GET {{baseUrl}}games/acao/1


### GamesController CREATE
POST {{baseUrl}}games
Content-type: application/json

{
    "name": "One",
    "categoryId": 2,
    "year": 1994
}


### GamesController->patch
PATCH {{baseUrl}}games/1
Content-type: application/json

{
    "categoryId":1
}


### GamesController->delete
DELETE {{baseUrl}}games/2
