@baseUrl = http://localhost:3000/

### AppController->Home
# @name AppControllerHome
GET {{baseUrl}}hello/world


### BaseManualController->getHello
# @name BaseManualControllerHome
GET {{baseUrl}}


### BaseCliController->home
# @name BaseCliControllerHome
GET {{baseUrl}}/base-cli


### BaseCliController->about
# @name BaseCliControllerAbout
GET {{baseUrl}}base-cli/about


# --------- GAMES ---------------

### GamesController->all
# @name GamesControllerAllc
GET {{baseUrl}}games?pagination=5&offset=3


### GamesController->findOne
GET {{baseUrl}}games/24


### GamesController->findOneByCategory
# @name GamesControllerByCategoryNameAndId
GET {{baseUrl}}games/terror/19


### GamesController create

# @name GameController->create
POST {{baseUrl}}games
Content-type: application/json

{
    "name": "Resident Evil",
    "categoryId": 20,
    "year": 2015
}


### GamesController->patch
PATCH {{baseUrl}}games/17
Content-type: application/json

{
    "name": "Bomber Man 3",
    "categoryId": 27
}


### GamesController->delete
DELETE {{baseUrl}}games/1


### ----------- CATEGORY

# --------- GAMES ---------------

### CategoryController->all
# @name CategoryControllerAll
GET {{baseUrl}}categories?pagination=5&offset=3


### CategoriesController->findOne
GET {{baseUrl}}categories/25


### CategoriesController create

# @name CategoryController->create
POST {{baseUrl}}categories
Content-type: application/json

{
    "name": "Sobrevivência",
    "slug": "sobrevivencia"
}


### CategoriesController->update
PATCH {{baseUrl}}categories/20
Content-type: application/json

{
    "name": "Terror",
    "slug": "terror"
}


### CategoriesController->delete
DELETE {{baseUrl}}categories/26


# ------------- USERS ----------------

### UsersController :: signup
POST {{baseUrl}}users/signup
Content-type: application/json

{
    "name": "Rich",
    "email": "rich2@email.com",
    "password": "123456"
}


### UsersController :: update
PATCH {{baseUrl}}users/5
Content-type: application/json

{
    "name": "Rich 2",
    "email": "rich2@email.com",
    "password": "senha-nova"
}